version: '3.8'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "StrongPassw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app_network

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sql_server
    networks:
      - app_network
      
      

networks:
  app_network: